// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/12/2025, 2:17:33 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/nick/Projects/apps/andreevka_landing/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/nick/Projects/apps/andreevka_landing/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/nick/Projects/apps/andreevka_landing/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/nick/Projects/apps/andreevka_landing/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/nick/Projects/apps/andreevka_landing/plugins/**/*.{js,ts,mjs}","/home/nick/Projects/apps/andreevka_landing/composables/**/*.{js,ts,mjs}","/home/nick/Projects/apps/andreevka_landing/utils/**/*.{js,ts,mjs}","/home/nick/Projects/apps/andreevka_landing/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/nick/Projects/apps/andreevka_landing/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/nick/Projects/apps/andreevka_landing/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/nick/Projects/apps/andreevka_landing/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;